### ISSUE TITLE
KADEPT Shield Flips Vessel

### ISSUE THREAD

**Issue by dtoxic47** [linuxgurugamer/Tokamak-Refurbished-Parts#22]
Putting the shield on LanderCan(or anyother vessel) flips the vessel when expanded (it obviously should not do that) when entering atmosphere [to reproduce put a KADEPT shiled on Lander can enter atmosphere, expand the shield and watch your kerbals roast :) ] 

Problem with "dragmodeltype"? "maximum_drag"? also noticed that it misses "ModuleLiftingSurface" like the one stock shield has (intentional?)
**MODULE
	{
		name = ModuleLiftingSurface
		useInternalDragModel = False
		deflectionLiftCoeff = 0.0875
		liftingSurfaceCurve = CapsuleBottom
		disableBodyLift = False
		omnidirectional = False
		perpendicularOnly = True
		transformDir = Y
		transformSign = -1
		nodeEnabled = True
		attachNodeName = bottom
	}**

@linuxgurugamer when you get the chance please take a look at this, thx
Edit: this is on ksp 1.9.0-1.9.1

**Comment by linuxgurugamer** [comment]
It is a very old part, I'll look at it in the next day or so

**Comment by linuxgurugamer** [comment]
Took a quick look.  You didn't tell me which one you were using

CoM looks okish, but it is very light.
I used the Large Kadept shield, and compared it to the Inflatable Heat Shield since they are the most similar.
The Inflatable doesn't have the ModuleLiftingSurface either.
I also noticed that there is very little ablator.

I'll adjust all of the Kadept heat shields.  I have the large one now working similar to the inflatable heat shield, will use the same settings on the others.

Hope to have something out by tomorrow

**Comment by dtoxic47** [comment]
Sorry,forgot to mention that, i was using the 1.25m on the lander can,i look at this as soon i get home

**Comment by linuxgurugamer** [comment]
I have not yet updated it, wait until I get a new release out

**Comment by linuxgurugamer** [comment]
Just released an update which fixes this issue
